In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('dirty_cafe_sales.csv')

print(df.shape)

In [7]:
print(df.dtypes)

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [9]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [27]:
df= df.replace(['ERROR','UNKNOWN'], np.nan)
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [15]:
for col in ['Quantity', 'Price Per Unit' , 'Total Spent']:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df.dtypes

In [19]:
df.describe()

          Quantity  Price Per Unit  Total Spent
count  9521.000000     9467.000000  9498.000000
mean      3.028463        2.949984     8.924352
std       1.419007        1.278450     6.009919
min       1.000000        1.000000     1.000000
25%       2.000000        2.000000     4.000000
50%       3.000000        3.000000     8.000000
75%       4.000000        4.000000    12.000000
max       5.000000        5.000000    25.000000

In [23]:
df.dtypes

Transaction ID       object
Item                 object
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
dtype: object

In [29]:
df.head(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [31]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

In [35]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].mean())

In [37]:
df['Total Spent'] = df['Total Spent'].fillna(df['Total Spent'].mean())

In [41]:
df.tail(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2.0,2.000000,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,2.949984,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.000000,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.949984,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.000000,12.0,Cash,In-store,2023-11-07

In [45]:
df['Item'] = df['Item'].fillna('Unknown')

In [47]:
df['Location']= df['Location'].fillna('Unknown')

In [55]:
df['Payment Method'] = df['Payment Method'].fillna('Unknown')

In [57]:
df.tail(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,PaymentMethod
9995,TXN_7672686,Coffee,2.0,2.000000,4.0,Unknown,Unknown,2023-08-30,Unknown
9996,TXN_9659401,Unknown,3.0,2.949984,3.0,Digital Wallet,Unknown,2023-06-02,Digital Wallet
9997,TXN_5255387,Coffee,4.0,2.000000,8.0,Digital Wallet,Unknown,2023-03-02,Digital Wallet
9998,TXN_7695629,Cookie,3.0,2.949984,3.0,Digital Wallet,Unknown,2023-12-02,Digital Wallet
9999,TXN_6170729,Sandwich,3.0,4.000000,12.0,Cash,In-store,2023-11-07,Cash

In [63]:
df = df.dropna(subset=['Transaction Date'])

In [65]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
PaymentMethod       0
dtype: int64

print(df.duplicated().sum())

In [67]:
df = df.drop_duplicates()

In [69]:
print(df.shape)

(9540, 9)

In [71]:
df.duplicated().sum()

0

In [77]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [79]:
df.dtypes

Transaction ID              object
Item                        object
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
PaymentMethod               object
dtype: object

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9540 non-null   float64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
 8   PaymentMethod     9540 non-null   object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 745.3+ KB

In [83]:
df.describe()

          Quantity  Price Per Unit  Total Spent               Transaction Date
count  9540.000000     9540.000000  9540.000000                           9540
mean      3.025464        2.950020     8.914936  2023-07-01 23:00:31.698113536
min       1.000000        1.000000     1.000000            2023-01-01 00:00:00
25%       2.000000        2.000000     4.000000            2023-04-01 00:00:00
50%       3.000000        3.000000     8.000000            2023-07-02 00:00:00
75%       4.000000        4.000000    12.000000            2023-10-02 00:00:00
max       5.000000        5.000000    25.000000            2023-12-31 00:00:00
std       1.384176        1.243399     5.858434                            NaN

In [85]:
df['Payment Method'].value_counts()

Payment Method
Unknown           3015
Digital Wallet    2197
Credit Card       2170
Cash              2158
Name: count, dtype: int64

In [87]:
df['PaymentMethod'].value_counts()

PaymentMethod
Unknown           3015
Digital Wallet    2197
Credit Card       2170
Cash              2158
Name: count, dtype: int64

In [93]:
df = df.drop(columns=['PaymentMethod'])

In [95]:
df.head(2)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9540 non-null   float64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 928.8+ KB

In [99]:
df.describe()

          Quantity  Price Per Unit  Total Spent               Transaction Date
count  9540.000000     9540.000000  9540.000000                           9540
mean      3.025464        2.950020     8.914936  2023-07-01 23:00:31.698113536
min       1.000000        1.000000     1.000000            2023-01-01 00:00:00
25%       2.000000        2.000000     4.000000            2023-04-01 00:00:00
50%       3.000000        3.000000     8.000000            2023-07-02 00:00:00
75%       4.000000        4.000000    12.000000            2023-10-02 00:00:00
max       5.000000        5.000000    25.000000            2023-12-31 00:00:00
std       1.384176        1.243399     5.858434                            NaN

In [101]:
print (df.duplicated().sum())

0

In [103]:
df = df.drop_duplicates()

In [105]:
print(df.shape)

(9540, 8)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9540 non-null   float64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 928.8+ KB

In [109]:
df.describe()

          Quantity  Price Per Unit  Total Spent               Transaction Date
count  9540.000000     9540.000000  9540.000000                           9540
mean      3.025464        2.950020     8.914936  2023-07-01 23:00:31.698113536
min       1.000000        1.000000     1.000000            2023-01-01 00:00:00
25%       2.000000        2.000000     4.000000            2023-04-01 00:00:00
50%       3.000000        3.000000     8.000000            2023-07-02 00:00:00
75%       4.000000        4.000000    12.000000            2023-10-02 00:00:00
max       5.000000        5.000000    25.000000            2023-12-31 00:00:00
std       1.384176        1.243399     5.858434                            NaN

In [111]:
df.to_csv('cafe_sales_cleaned.csv' , index=False)